#define AmericaIsGreat return
#define AsLongAs for
#define AsSameAs ==
#define is =
#define in <=
#define final const
#define fact true
#define lie false
#define useless void
#define nothing 0
#define more ,
#define over ;
#define left {
#define right }
#define number int
#define import using
#define package namespace
#define final const
#define bigger ++
#define object struct
#define Start main
#define plus +
